[2022-11-06 23:31:44,781] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:44,782] [plex_meta_manager.py:134]  [INFO]     |                                                                                                    |
[2022-11-06 23:31:44,782] [plex_meta_manager.py:135]  [INFO]     |        ____  _             __  __      _          __  __                                           |
[2022-11-06 23:31:44,782] [plex_meta_manager.py:136]  [INFO]     |       |  _ \| | _____  __ |  \/  | ___| |_ __ _  |  \/  | __ _ _ __   __ _  __ _  ___ _ __         |
[2022-11-06 23:31:44,782] [plex_meta_manager.py:137]  [INFO]     |       | |_) | |/ _ \ \/ / | |\/| |/ _ \ __/ _` | | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|        |
[2022-11-06 23:31:44,782] [plex_meta_manager.py:138]  [INFO]     |       |  __/| |  __/>  <  | |  | |  __/ || (_| | | |  | | (_| | | | | (_| | (_| |  __/ |           |
[2022-11-06 23:31:44,783] [plex_meta_manager.py:139]  [INFO]     |       |_|   |_|\___/_/\_\ |_|  |_|\___|\__\__,_| |_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|           |
[2022-11-06 23:31:44,783] [plex_meta_manager.py:140]  [INFO]     |                                                                            |___/                   |
[2022-11-06 23:31:44,783] [plex_meta_manager.py:141]  [INFO]     |     Version: 1.15.0                                                                                |
[2022-11-06 23:31:44,783] [util.py:207]               [DEBUG]    |====================================================================================================|
[2022-11-06 23:31:44,783] [plex_meta_manager.py:152]  [DEBUG]    | --config (PMM_CONFIG): None                                                                        |
[2022-11-06 23:31:44,784] [plex_meta_manager.py:153]  [DEBUG]    | --time (PMM_TIME): 03:00                                                                           |
[2022-11-06 23:31:44,784] [plex_meta_manager.py:154]  [DEBUG]    | --run (PMM_RUN): True                                                                              |
[2022-11-06 23:31:44,784] [plex_meta_manager.py:155]  [DEBUG]    | --run-tests (PMM_TEST): False                                                                      |
[2022-11-06 23:31:44,784] [plex_meta_manager.py:156]  [DEBUG]    | --collections-only (PMM_COLLECTIONS_ONLY): False                                                   |
[2022-11-06 23:31:44,784] [plex_meta_manager.py:157]  [DEBUG]    | --libraries-only (PMM_LIBRARIES_ONLY): False                                                       |
[2022-11-06 23:31:44,784] [plex_meta_manager.py:158]  [DEBUG]    | --libraries-first (PMM_LIBRARIES_FIRST): False                                                     |
[2022-11-06 23:31:44,784] [plex_meta_manager.py:159]  [DEBUG]    | --run-collections (PMM_COLLECTIONS): None                                                          |
[2022-11-06 23:31:44,784] [plex_meta_manager.py:160]  [DEBUG]    | --run-libraries (PMM_LIBRARIES): None                                                              |
[2022-11-06 23:31:44,785] [plex_meta_manager.py:161]  [DEBUG]    | --ignore-schedules (PMM_IGNORE_SCHEDULES): False                                                   |
[2022-11-06 23:31:44,785] [plex_meta_manager.py:162]  [DEBUG]    | --delete-collections (PMM_DELETE_COLLECTIONS): False                                               |
[2022-11-06 23:31:44,785] [plex_meta_manager.py:163]  [DEBUG]    | --resume (PMM_RESUME): None                                                                        |
[2022-11-06 23:31:44,785] [plex_meta_manager.py:164]  [DEBUG]    | --no-countdown (PMM_NO_COUNTDOWN): False                                                           |
[2022-11-06 23:31:44,785] [plex_meta_manager.py:165]  [DEBUG]    | --no-missing (PMM_NO_MISSING): False                                                               |
[2022-11-06 23:31:44,785] [plex_meta_manager.py:166]  [DEBUG]    | --read-only-config (PMM_READ_ONLY_CONFIG): False                                                   |
[2022-11-06 23:31:44,785] [plex_meta_manager.py:167]  [DEBUG]    | --divider (PMM_DIVIDER): =                                                                         |
[2022-11-06 23:31:44,786] [plex_meta_manager.py:168]  [DEBUG]    | --width (PMM_WIDTH): 100                                                                           |
[2022-11-06 23:31:44,786] [plex_meta_manager.py:169]  [DEBUG]    | --debug (PMM_DEBUG): False                                                                         |
[2022-11-06 23:31:44,786] [plex_meta_manager.py:170]  [DEBUG]    | --trace (PMM_TRACE): False                                                                         |
[2022-11-06 23:31:44,786] [plex_meta_manager.py:171]  [DEBUG]    |                                                                                                    |
[2022-11-06 23:31:44,786] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:44,786] [util.py:216]               [INFO]     |                                            Starting Run                                            |
[2022-11-06 23:31:44,787] [util.py:220]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:44,787] [config.py:37]              [INFO]     | Locating config...                                                                                 |
[2022-11-06 23:31:44,787] [config.py:43]              [INFO]     | Using C:\Plex-Stack\Plex-Meta-Manager\config\config.yml as config                                  |
[2022-11-06 23:31:44,824] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:44,825] [cache.py:17]               [INFO]     | Initializing cache database at C:\Plex-Stack\Plex-Meta-Manager\config\config.cache                 |
[2022-11-06 23:31:44,826] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:44,826] [config.py:313]             [INFO]     | Connecting to Notifiarr...                                                                         |
[2022-11-06 23:31:44,827] [util.py:162]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 316, in __init__
                                                                 |     "apikey": check_for_attribute(self.data, "apikey", parent="notifiarr", throw=True),
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 251, in check_for_attribute
                                                                 |     raise Failed(f"Config Error: {message}")
                                                                 | modules.util.Failed: Config Error: notifiarr sub-attribute apikey is blank
                                                                 | 
[2022-11-06 23:31:44,828] [config.py:322]             [ERROR]    | Config Error: notifiarr sub-attribute apikey is blank
[2022-11-06 23:31:44,828] [config.py:323]             [INFO]     | Notifiarr Connection Failed
[2022-11-06 23:31:44,829] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:44,829] [config.py:341]             [INFO]     | Connecting to TMDb...                                                                              |
[2022-11-06 23:31:44,907] [config.py:346]             [INFO]     | TMDb Connection Successful                                                                         |
[2022-11-06 23:31:44,908] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:44,908] [config.py:354]             [INFO]     | Connecting to OMDb...                                                                              |
[2022-11-06 23:31:44,908] [config.py:359]             [ERROR]    | Config Error: omdb sub-attribute apikey is blank                                                   |
[2022-11-06 23:31:44,909] [config.py:360]             [INFO]     | OMDb Connection Failed                                                                             |
[2022-11-06 23:31:44,909] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:44,909] [config.py:368]             [INFO]     | Connecting to Trakt...                                                                             |
[2022-11-06 23:31:45,078] [config.py:379]             [INFO]     | Trakt Connection Successful                                                                        |
[2022-11-06 23:31:45,078] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:45,079] [config.py:387]             [INFO]     | Connecting to My Anime List...                                                                     |
[2022-11-06 23:31:45,750] [config.py:398]             [INFO]     | My Anime List Connection Successful                                                                |
[2022-11-06 23:31:45,750] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:45,751] [config.py:405]             [INFO]     | Connecting to AniDB...                                                                             |
[2022-11-06 23:31:49,947] [config.py:413]             [ERROR]    | AniDB Error: Login failed                                                                          |
[2022-11-06 23:31:49,949] [config.py:414]             [INFO]     | My Anime List Connection Successful                                                                |
[2022-11-06 23:31:49,950] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:49,950] [config.py:466]             [WARNING]  | playlist_files attribute not found                                                                 |
[2022-11-06 23:31:49,951] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:49,951] [config.py:486]             [INFO]     | Connecting to Plex Libraries...                                                                    |
[2022-11-06 23:31:49,952] [util.py:162]               [DEBUG]    | Config Warning: sonarr sub-attribute monitor: False is an invalid input using all as default       |
[2022-11-06 23:31:49,952] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:49,952] [util.py:216]               [INFO]     |                                        Movies Configuration                                        |
[2022-11-06 23:31:49,952] [util.py:220]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:49,953] [config.py:553]             [INFO]     |                                                                                                    |
[2022-11-06 23:31:49,953] [config.py:554]             [INFO]     | Connecting to Movies Library...                                                                    |
[2022-11-06 23:31:49,953] [util.py:162]               [DEBUG]    | Config Warning: missing_path attribute not found using None as default                             |
[2022-11-06 23:31:49,955] [meta.py:227]               [INFO]     | 
[2022-11-06 23:31:49,955] [meta.py:228]               [INFO]     | Loading Metadata File: config/Movie.yml
[2022-11-06 23:31:50,022] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-06 23:31:50,023] [meta.py:227]               [INFO]     | 
[2022-11-06 23:31:50,024] [meta.py:228]               [INFO]     | Loading Metadata File: config/Special_Genre.yml
[2022-11-06 23:31:50,036] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-06 23:31:50,037] [meta.py:227]               [INFO]     | 
[2022-11-06 23:31:50,037] [meta.py:228]               [INFO]     | Loading Metadata File: config/Studio.yml
[2022-11-06 23:31:50,060] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-06 23:31:50,060] [meta.py:227]               [INFO]     | 
[2022-11-06 23:31:50,060] [meta.py:228]               [INFO]     | Loading Metadata File: config/Holiday.yml
[2022-11-06 23:31:50,090] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-06 23:31:50,091] [meta.py:227]               [INFO]     | 
[2022-11-06 23:31:50,091] [meta.py:228]               [INFO]     | Loading Metadata File: config/Metadata.yml
[2022-11-06 23:31:50,792] [util.py:159]               [ERROR]    | YAML Error: mapping values are not allowed here
                                                                 | |	        in "<unicode string>", line 5060, column 56:
                                                                 | |	           ... /theposterdb.com/api/assets/year: 
                                                                 | |	                                               ^ (line: 5060)
[2022-11-06 23:31:50,797] [meta.py:227]               [INFO]     | 
[2022-11-06 23:31:50,797] [meta.py:228]               [INFO]     | Loading Metadata File: config/Overlays.yml
[2022-11-06 23:31:50,801] [meta.py:236]               [INFO]     | Metadata File Loaded Successfully
[2022-11-06 23:31:50,802] [library.py:123]            [INFO]     | 
[2022-11-06 23:31:50,802] [library.py:125]            [INFO]     | Using Asset Directory: config/assets
[2022-11-06 23:31:50,802] [plex.py:386]               [INFO]     | 
[2022-11-06 23:31:50,809] [config.py:748]             [INFO]     | Movies Library Connection Successful
[2022-11-06 23:31:50,809] [config.py:758]             [INFO]     | 
[2022-11-06 23:31:50,809] [util.py:216]               [INFO]     |======================================= Radarr Configuration =======================================|
[2022-11-06 23:31:50,809] [config.py:760]             [INFO]     |                                                                                                    |
[2022-11-06 23:31:50,809] [config.py:761]             [INFO]     | Connecting to Movies library's Radarr...                                                           |
[2022-11-06 23:31:50,810] [config.py:762]             [INFO]     |                                                                                                    |
[2022-11-06 23:31:50,834] [config.py:783]             [INFO]     | Movies library's Radarr Connection Successful                                                      |
[2022-11-06 23:31:50,834] [config.py:786]             [INFO]     |                                                                                                    |
[2022-11-06 23:31:50,835] [util.py:216]               [INFO]     |======================================= Sonarr Configuration =======================================|
[2022-11-06 23:31:50,835] [config.py:788]             [INFO]     |                                                                                                    |
[2022-11-06 23:31:50,836] [config.py:789]             [INFO]     | Connecting to Movies library's Sonarr...                                                           |
[2022-11-06 23:31:50,836] [config.py:790]             [INFO]     |                                                                                                    |
[2022-11-06 23:31:50,850] [config.py:814]             [INFO]     | Movies library's Sonarr Connection Successful                                                      |
[2022-11-06 23:31:50,851] [config.py:817]             [INFO]     |                                                                                                    |
[2022-11-06 23:31:50,851] [util.py:216]               [INFO]     |====================================== Tautulli Configuration ======================================|
[2022-11-06 23:31:50,851] [config.py:819]             [INFO]     |                                                                                                    |
[2022-11-06 23:31:50,851] [config.py:820]             [INFO]     | Connecting to Movies library's Tautulli...                                                         |
[2022-11-06 23:31:50,851] [config.py:821]             [INFO]     |                                                                                                    |
[2022-11-06 23:31:50,852] [util.py:162]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 825, in __init__
                                                                 |     "apikey": check_for_attribute(lib, "apikey", parent="tautulli", default=self.general["tautulli"]["apikey"], req_default=True, save=False)
                                                                 |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\config.py", line 241, in check_for_attribute
                                                                 |     raise Failed(f"Config Error: {attribute} attribute must be set under {parent} globally or under this specific Library")
                                                                 | modules.util.Failed: Config Error: apikey attribute must be set under tautulli globally or under this specific Library
                                                                 | 
[2022-11-06 23:31:50,852] [util.py:159]               [ERROR]    | Config Error: apikey attribute must be set under tautulli globally or under this specific Library
[2022-11-06 23:31:50,852] [config.py:831]             [INFO]     | 
[2022-11-06 23:31:50,853] [config.py:832]             [INFO]     | Movies library's Tautulli Connection Failed
[2022-11-06 23:31:50,853] [config.py:836]             [INFO]     | 
[2022-11-06 23:31:50,853] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:50,853] [config.py:842]             [INFO]     | 1 Plex Library Connection Successful                                                               |
[2022-11-06 23:31:50,853] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:50,855] [plex_meta_manager.py:216]  [INFO]     |                                                                                                    |
[2022-11-06 23:31:50,855] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:50,856] [util.py:216]               [INFO]     |                                           Movies Library                                           |
[2022-11-06 23:31:50,856] [util.py:220]               [INFO]     |====================================================================================================|
[2022-11-06 23:31:50,857] [plex_meta_manager.py:222]  [DEBUG]    |                                                                                                    |
[2022-11-06 23:31:50,857] [plex_meta_manager.py:223]  [DEBUG]    | Mapping Name: Movies                                                                               |
[2022-11-06 23:31:50,858] [plex_meta_manager.py:224]  [DEBUG]    | Folder Name: Movies                                                                                |
[2022-11-06 23:31:50,858] [plex_meta_manager.py:225]  [DEBUG]    | Missing Path: C:\Plex-Stack\Plex-Meta-Manager\config\Movies_missing.yml                            |
[2022-11-06 23:31:50,858] [plex_meta_manager.py:227]  [DEBUG]    | Asset Directory: config/assets                                                                     |
[2022-11-06 23:31:50,859] [plex_meta_manager.py:228]  [DEBUG]    | Asset Folders: False                                                                               |
[2022-11-06 23:31:50,859] [plex_meta_manager.py:229]  [DEBUG]    | Create Asset Folders: False                                                                        |
[2022-11-06 23:31:50,860] [plex_meta_manager.py:230]  [DEBUG]    | Download URL Assets: False                                                                         |
[2022-11-06 23:31:50,860] [plex_meta_manager.py:231]  [DEBUG]    | Sync Mode: append                                                                                  |
[2022-11-06 23:31:50,860] [plex_meta_manager.py:232]  [DEBUG]    | Collection Minimum: 1                                                                              |
[2022-11-06 23:31:50,861] [plex_meta_manager.py:233]  [DEBUG]    | Delete Below Minimum: True                                                                         |
[2022-11-06 23:31:50,861] [plex_meta_manager.py:234]  [DEBUG]    | Delete Not Scheduled: False                                                                        |
[2022-11-06 23:31:50,861] [plex_meta_manager.py:235]  [DEBUG]    | Default Collection Order: release                                                                  |
[2022-11-06 23:31:50,861] [plex_meta_manager.py:236]  [DEBUG]    | Missing Only Released: False                                                                       |
[2022-11-06 23:31:50,862] [plex_meta_manager.py:237]  [DEBUG]    | Only Filter Missing: False                                                                         |
[2022-11-06 23:31:50,862] [plex_meta_manager.py:238]  [DEBUG]    | Show Unmanaged: True                                                                               |
[2022-11-06 23:31:50,862] [plex_meta_manager.py:239]  [DEBUG]    | Show Filtered: False                                                                               |
[2022-11-06 23:31:50,862] [plex_meta_manager.py:240]  [DEBUG]    | Show Missing: True                                                                                 |
[2022-11-06 23:31:50,863] [plex_meta_manager.py:241]  [DEBUG]    | Show Missing Assets: False                                                                         |
[2022-11-06 23:31:50,864] [plex_meta_manager.py:242]  [DEBUG]    | Save Missing: True                                                                                 |
[2022-11-06 23:31:50,864] [plex_meta_manager.py:243]  [DEBUG]    | Clean Bundles: False                                                                               |
[2022-11-06 23:31:50,864] [plex_meta_manager.py:244]  [DEBUG]    | Empty Trash: False                                                                                 |
[2022-11-06 23:31:50,864] [plex_meta_manager.py:245]  [DEBUG]    | Optimize: False                                                                                    |
[2022-11-06 23:31:50,865] [plex_meta_manager.py:246]  [DEBUG]    | Timeout: 60                                                                                        |
[2022-11-06 23:31:50,865] [plex_meta_manager.py:256]  [INFO]     |                                                                                                    |
[2022-11-06 23:31:50,865] [util.py:216]               [INFO]     |====================================== Mapping Movies Library ======================================|
[2022-11-06 23:31:50,866] [plex_meta_manager.py:258]  [INFO]     |                                                                                                    |
[2022-11-06 23:31:50,866] [plex.py:456]               [INFO]     | Loading All Movies from Library: Movies                                                            |
[2022-11-06 23:33:07,099] [util.py:209]               [INFO]     |====================================================================================================|
[2022-11-06 23:33:07,099] [util.py:216]               [INFO]     |                                     Exiting Plex Meta Manager                                      |
[2022-11-06 23:33:07,100] [util.py:220]               [INFO]     |====================================================================================================|
