[2022-10-23 01:10:35,556] [util.py:209]               [INFO]     |====================================================================================================|
[2022-10-23 01:10:35,556] [util.py:216]               [INFO]     |                                   Pandemic Collection in Movies                                    |
[2022-10-23 01:10:35,557] [util.py:220]               [INFO]     |====================================================================================================|
[2022-10-23 01:10:35,557] [plex_meta_manager.py:750]  [INFO]     |                                                                                                    |
[2022-10-23 01:10:35,557] [util.py:216]               [INFO]     |================================== Validating Pandemic Attributes ==================================|
[2022-10-23 01:10:35,558] [builder.py:265]            [DEBUG]    |                                                                                                    |
[2022-10-23 01:10:35,558] [builder.py:266]            [DEBUG]    | Validating Method: template                                                                        |
[2022-10-23 01:10:35,558] [meta.py:83]                [DEBUG]    | Value: ordereddict([('name', 'Other Genre'), ('poster', 'https://theposterdb.com/api/assets/55837')]) |
[2022-10-23 01:10:35,559] [builder.py:330]            [DEBUG]    |                                                                                                    |
[2022-10-23 01:10:35,559] [builder.py:331]            [DEBUG]    | Validating Method: sync_mode                                                                       |
[2022-10-23 01:10:35,559] [builder.py:335]            [DEBUG]    | Value: sync                                                                                        |
[2022-10-23 01:10:35,560] [builder.py:453]            [DEBUG]    |                                                                                                    |
[2022-10-23 01:10:35,560] [builder.py:454]            [DEBUG]    | Validating Method: collection_order                                                                |
[2022-10-23 01:10:35,560] [builder.py:455]            [DEBUG]    | Value: alpha                                                                                       |
[2022-10-23 01:10:35,560] [builder.py:472]            [DEBUG]    |                                                                                                    |
[2022-10-23 01:10:35,561] [builder.py:473]            [DEBUG]    | Validating Method: imdb_list                                                                       |
[2022-10-23 01:10:35,562] [builder.py:474]            [DEBUG]    | Value: [ordereddict([('url', 'https://www.imdb.com/list/ls041901506/')]), ordereddict([('url', 'https://www.imdb.com/list/ls092321048/')])] |
[2022-10-23 01:10:40,557] [builder.py:472]            [DEBUG]    |                                                                                                    |
[2022-10-23 01:10:40,558] [builder.py:473]            [DEBUG]    | Validating Method: summary                                                                         |
[2022-10-23 01:10:40,558] [builder.py:474]            [DEBUG]    | Value: A Pandemic film resolves around widespread viruses, plagues, and diseases.                  |
[2022-10-23 01:10:40,558] [builder.py:472]            [DEBUG]    |                                                                                                    |
[2022-10-23 01:10:40,559] [builder.py:473]            [DEBUG]    | Validating Method: sort_title                                                                      |
[2022-10-23 01:10:40,559] [builder.py:474]            [DEBUG]    | Value: 00000d_Pandemic                                                                             |
[2022-10-23 01:10:40,559] [builder.py:472]            [DEBUG]    |                                                                                                    |
[2022-10-23 01:10:40,559] [builder.py:473]            [DEBUG]    | Validating Method: url_poster                                                                      |
[2022-10-23 01:10:40,560] [builder.py:474]            [DEBUG]    | Value: https://theposterdb.com/api/assets/55837                                                    |
[2022-10-23 01:10:40,763] [builder.py:619]            [INFO]     |                                                                                                    |
[2022-10-23 01:10:40,763] [builder.py:620]            [INFO]     | Validation Successful                                                                              |
[2022-10-23 01:10:40,775] [plex_meta_manager.py:758]  [INFO]     |                                                                                                    |
[2022-10-23 01:10:40,775] [util.py:216]               [INFO]     |=================================== Running Pandemic Collection ====================================|
[2022-10-23 01:10:40,775] [plex_meta_manager.py:773]  [INFO]     |                                                                                                    |
[2022-10-23 01:10:40,776] [plex_meta_manager.py:774]  [INFO]     | Sync Mode: sync                                                                                    |
[2022-10-23 01:10:40,776] [builder.py:1275]           [DEBUG]    |                                                                                                    |
[2022-10-23 01:10:40,776] [builder.py:1276]           [DEBUG]    | Builder: imdb_list: {'url': 'https://www.imdb.com/list/ls041901506/', 'limit': 0}                  |
[2022-10-23 01:10:40,776] [builder.py:1277]           [INFO]     |                                                                                                    |
[2022-10-23 01:10:40,777] [imdb.py:158]               [INFO]     | Processing IMDb List: https://www.imdb.com/list/ls041901506/                                       |
[2022-10-23 01:10:46,012] [imdb.py:127]               [DEBUG]    | 52 IMDb IDs Found: ['tt3148266', 'tt0429422', 'tt1598778', 'tt0234634', 'tt0115123', 'tt0816711', 'tt1258189', 'tt1318514', 'tt0285331', 'tt3163224', 'tt3774802', 'tt0802821', 'tt0272557', 'tt0275039', 'tt5700672', 'tt6656238', 'tt4132692', 'tt2758950', 'tt0221885', 'tt0115309', 'tt4209174', 'tt5092380', 'tt0806203', 'tt1414863', 'tt2351310', 'tt8850222', 'tt0424600', 'tt3860916', 'tt0411011', 'tt0118480', 'tt0155716', 'tt3458254', 'tt0105206', 'tt0479201', 'tt0119984', 'tt8551868', 'tt1410198', 'tt0250214', 'tt3709718', 'tt1754316', 'tt0462097', 'tt4839118', 'tt6013156', 'tt0125034', 'tt7403736', 'tt8365426', 'tt4291700', 'tt0118885', 'tt2351310', 'tt4348012', 'tt0115471', 'tt1587669'] |
[2022-10-23 01:10:46,012] [builder.py:1282]           [DEBUG]    |                                                                                                    |
[2022-10-23 01:10:46,013] [builder.py:1283]           [DEBUG]    | 52 IDs Found: [('tt3148266', 'imdb'), ('tt0429422', 'imdb'), ('tt1598778', 'imdb'), ('tt0234634', 'imdb'), ('tt0115123', 'imdb'), ('tt0816711', 'imdb'), ('tt1258189', 'imdb'), ('tt1318514', 'imdb'), ('tt0285331', 'imdb'), ('tt3163224', 'imdb'), ('tt3774802', 'imdb'), ('tt0802821', 'imdb'), ('tt0272557', 'imdb'), ('tt0275039', 'imdb'), ('tt5700672', 'imdb'), ('tt6656238', 'imdb'), ('tt4132692', 'imdb'), ('tt2758950', 'imdb'), ('tt0221885', 'imdb'), ('tt0115309', 'imdb'), ('tt4209174', 'imdb'), ('tt5092380', 'imdb'), ('tt0806203', 'imdb'), ('tt1414863', 'imdb'), ('tt2351310', 'imdb'), ('tt8850222', 'imdb'), ('tt0424600', 'imdb'), ('tt3860916', 'imdb'), ('tt0411011', 'imdb'), ('tt0118480', 'imdb'), ('tt0155716', 'imdb'), ('tt3458254', 'imdb'), ('tt0105206', 'imdb'), ('tt0479201', 'imdb'), ('tt0119984', 'imdb'), ('tt8551868', 'imdb'), ('tt1410198', 'imdb'), ('tt0250214', 'imdb'), ('tt3709718', 'imdb'), ('tt1754316', 'imdb'), ('tt0462097', 'imdb'), ('tt4839118', 'imdb'), ('tt6013156', 'imdb'), ('tt0125034', 'imdb'), ('tt7403736', 'imdb'), ('tt8365426', 'imdb'), ('tt4291700', 'imdb'), ('tt0118885', 'imdb'), ('tt2351310', 'imdb'), ('tt4348012', 'imdb'), ('tt0115471', 'imdb'), ('tt1587669', 'imdb')] |
[2022-10-23 01:10:46,013] [builder.py:1284]           [DEBUG]    |                                                                                                    |
[2022-10-23 01:10:47,414] [builder.py:1383]           [ERROR]    | Convert Error: No TVDb ID Found for TMDb ID: 75671                                                 |
[2022-10-23 01:10:47,677] [builder.py:1275]           [DEBUG]    |                                                                                                    |
[2022-10-23 01:10:47,678] [builder.py:1276]           [DEBUG]    | Builder: imdb_list: {'url': 'https://www.imdb.com/list/ls092321048/', 'limit': 0}                  |
[2022-10-23 01:10:47,678] [builder.py:1277]           [INFO]     |                                                                                                    |
[2022-10-23 01:10:47,678] [imdb.py:158]               [INFO]     | Processing IMDb List: https://www.imdb.com/list/ls092321048/                                       |
[2022-10-23 01:10:55,819] [imdb.py:127]               [DEBUG]    | 84 IMDb IDs Found: ['tt0108941', 'tt0114069', 'tt0114746', 'tt0120804', 'tt0289043', 'tt0463854', 'tt0303816', 'tt0363547', 'tt0365748', 'tt0318627', 'tt2592614', 'tt0432021', 'tt0961722', 'tt3832096', 'tt1082868', 'tt0455407', 'tt1598778', 'tt0816711', 'tt2281159', 'tt0806203', 'tt2351310', 'tt4421578', 'tt1226681', 'tt0861689', 'tt4547056', 'tt3860916', 'tt8941440', 'tt3774802', 'tt2580382', 'tt0434409', 'tt0069895', 'tt0074292', 'tt0480249', 'tt1699231', 'tt1520211', 'tt4131818', 'tt0120755', 'tt4500922', 'tt2246907', 'tt5700672', 'tt1038988', 'tt1245112', 'tt0120458', 'tt0117500', 'tt1560220', 'tt1156398', 'tt0077402', 'tt7949218', 'tt3148266', 'tt0206634', 'tt2737304', 'tt0898367', 'tt0446755', 'tt0424600', 'tt0066769', 'tt0419706', 'tt0762073', 'tt3458254', 'tt2102496', 'tt1077258', 'tt2638662', 'tt0800026', 'tt0118885', 'tt0272557', 'tt0429422', 'tt0234634', 'tt1258189', 'tt0285331', 'tt5868826', 'tt0388482', 'tt3062096', 'tt1528100', 'tt0483607', 'tt0073705', 'tt3463106', 'tt1881002', 'tt2597892', 'tt4974778', 'tt1831804', 'tt0108941', 'tt1258189', 'tt2654620', 'tt7366338', 'tt10384106'] |
[2022-10-23 01:10:55,820] [builder.py:1282]           [DEBUG]    |                                                                                                    |
[2022-10-23 01:10:55,820] [builder.py:1283]           [DEBUG]    | 84 IDs Found: [('tt0108941', 'imdb'), ('tt0114069', 'imdb'), ('tt0114746', 'imdb'), ('tt0120804', 'imdb'), ('tt0289043', 'imdb'), ('tt0463854', 'imdb'), ('tt0303816', 'imdb'), ('tt0363547', 'imdb'), ('tt0365748', 'imdb'), ('tt0318627', 'imdb'), ('tt2592614', 'imdb'), ('tt0432021', 'imdb'), ('tt0961722', 'imdb'), ('tt3832096', 'imdb'), ('tt1082868', 'imdb'), ('tt0455407', 'imdb'), ('tt1598778', 'imdb'), ('tt0816711', 'imdb'), ('tt2281159', 'imdb'), ('tt0806203', 'imdb'), ('tt2351310', 'imdb'), ('tt4421578', 'imdb'), ('tt1226681', 'imdb'), ('tt0861689', 'imdb'), ('tt4547056', 'imdb'), ('tt3860916', 'imdb'), ('tt8941440', 'imdb'), ('tt3774802', 'imdb'), ('tt2580382', 'imdb'), ('tt0434409', 'imdb'), ('tt0069895', 'imdb'), ('tt0074292', 'imdb'), ('tt0480249', 'imdb'), ('tt1699231', 'imdb'), ('tt1520211', 'imdb'), ('tt4131818', 'imdb'), ('tt0120755', 'imdb'), ('tt4500922', 'imdb'), ('tt2246907', 'imdb'), ('tt5700672', 'imdb'), ('tt1038988', 'imdb'), ('tt1245112', 'imdb'), ('tt0120458', 'imdb'), ('tt0117500', 'imdb'), ('tt1560220', 'imdb'), ('tt1156398', 'imdb'), ('tt0077402', 'imdb'), ('tt7949218', 'imdb'), ('tt3148266', 'imdb'), ('tt0206634', 'imdb'), ('tt2737304', 'imdb'), ('tt0898367', 'imdb'), ('tt0446755', 'imdb'), ('tt0424600', 'imdb'), ('tt0066769', 'imdb'), ('tt0419706', 'imdb'), ('tt0762073', 'imdb'), ('tt3458254', 'imdb'), ('tt2102496', 'imdb'), ('tt1077258', 'imdb'), ('tt2638662', 'imdb'), ('tt0800026', 'imdb'), ('tt0118885', 'imdb'), ('tt0272557', 'imdb'), ('tt0429422', 'imdb'), ('tt0234634', 'imdb'), ('tt1258189', 'imdb'), ('tt0285331', 'imdb'), ('tt5868826', 'imdb'), ('tt0388482', 'imdb'), ('tt3062096', 'imdb'), ('tt1528100', 'imdb'), ('tt0483607', 'imdb'), ('tt0073705', 'imdb'), ('tt3463106', 'imdb'), ('tt1881002', 'imdb'), ('tt2597892', 'imdb'), ('tt4974778', 'imdb'), ('tt1831804', 'imdb'), ('tt0108941', 'imdb'), ('tt1258189', 'imdb'), ('tt2654620', 'imdb'), ('tt7366338', 'imdb'), ('tt10384106', 'imdb')] |
[2022-10-23 01:10:55,820] [builder.py:1284]           [DEBUG]    |                                                                                                    |
[2022-10-23 01:11:47,566] [util.py:162]               [DEBUG]    | Traceback (most recent call last):                                                                 |
[2022-10-23 01:11:47,566] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\requests\models.py", line 910, in json |
[2022-10-23 01:11:47,566] [util.py:162]               [DEBUG]    |     return complexjson.loads(self.text, **kwargs)                                                  |
[2022-10-23 01:11:47,567] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads |
[2022-10-23 01:11:47,567] [util.py:162]               [DEBUG]    |     return _default_decoder.decode(s)                                                              |
[2022-10-23 01:11:47,567] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode |
[2022-10-23 01:11:47,567] [util.py:162]               [DEBUG]    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                              |
[2022-10-23 01:11:47,568] [util.py:162]               [DEBUG]    |   File "C:\Users\Jack\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode |
[2022-10-23 01:11:47,568] [util.py:162]               [DEBUG]    |     raise JSONDecodeError("Expecting value", s, err.value) from None                               |
[2022-10-23 01:11:47,568] [util.py:162]               [DEBUG]    | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                            |
[2022-10-23 01:11:47,568] [util.py:162]               [DEBUG]    |                                                                                                    |
[2022-10-23 01:11:47,568] [util.py:162]               [DEBUG]    | During handling of the above exception, another exception occurred:                                |
[2022-10-23 01:11:47,569] [util.py:162]               [DEBUG]    |                                                                                                    |
[2022-10-23 01:11:47,569] [util.py:162]               [DEBUG]    | Traceback (most recent call last):                                                                 |
[2022-10-23 01:11:47,569] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\plex_meta_manager.py", line 783, in run_collection         |
[2022-10-23 01:11:47,569] [util.py:162]               [DEBUG]    |     builder.find_rating_keys()                                                                     |
[2022-10-23 01:11:47,570] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\builder.py", line 1379, in find_rating_keys        |
[2022-10-23 01:11:47,570] [util.py:162]               [DEBUG]    |     tvdb_id = self.config.Convert.tmdb_to_tvdb(tmdb_id, fail=True)                                 |
[2022-10-23 01:11:47,570] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\convert.py", line 149, in tmdb_to_tvdb             |
[2022-10-23 01:11:47,571] [util.py:162]               [DEBUG]    |     tvdb_id = self.config.TMDb.convert_from(tmdb_id, "tvdb_id", False)                             |
[2022-10-23 01:11:47,571] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\retrying.py", line 49, in wrapped_f |
[2022-10-23 01:11:47,571] [util.py:162]               [DEBUG]    |     return Retrying(*dargs, **dkw).call(f, *args, **kw)                                            |
[2022-10-23 01:11:47,572] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\retrying.py", line 212, in call |
[2022-10-23 01:11:47,572] [util.py:162]               [DEBUG]    |     raise attempt.get()                                                                            |
[2022-10-23 01:11:47,572] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\retrying.py", line 247, in get  |
[2022-10-23 01:11:47,572] [util.py:162]               [DEBUG]    |     six.reraise(self.value[0], self.value[1], self.value[2])                                       |
[2022-10-23 01:11:47,573] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\six.py", line 719, in reraise   |
[2022-10-23 01:11:47,573] [util.py:162]               [DEBUG]    |     raise value                                                                                    |
[2022-10-23 01:11:47,573] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\retrying.py", line 200, in call |
[2022-10-23 01:11:47,573] [util.py:162]               [DEBUG]    |     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)                                  |
[2022-10-23 01:11:47,573] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\modules\tmdb.py", line 91, in convert_from                 |
[2022-10-23 01:11:47,574] [util.py:162]               [DEBUG]    |     id_to_return = self.Movie.external_ids(tmdb_id)[convert_to] if is_movie else self.TV.external_ids(tmdb_id)[convert_to] |
[2022-10-23 01:11:47,574] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\tmdbv3api\objs\tv.py", line 149, in external_ids |
[2022-10-23 01:11:47,574] [util.py:162]               [DEBUG]    |     self._call(self._urls["external_ids"] % (str(id)), ""), None                                   |
[2022-10-23 01:11:47,574] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\tmdbv3api\tmdb.py", line 156, in _call |
[2022-10-23 01:11:47,575] [util.py:162]               [DEBUG]    |     json = req.json()                                                                              |
[2022-10-23 01:11:47,575] [util.py:162]               [DEBUG]    |   File "C:\Plex-Stack\Plex-Meta-Manager\pmm-venv\lib\site-packages\requests\models.py", line 917, in json |
[2022-10-23 01:11:47,575] [util.py:162]               [DEBUG]    |     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)                                             |
[2022-10-23 01:11:47,575] [util.py:162]               [DEBUG]    | requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0                                   |
[2022-10-23 01:11:47,576] [util.py:162]               [DEBUG]    |                                                                                                    |
[2022-10-23 01:11:47,576] [plex_meta_manager.py:877]  [ERROR]    | Unknown Error: [Errno Expecting value] : 0                                                         |
[2022-10-23 01:11:47,576] [plex_meta_manager.py:880]  [INFO]     |                                                                                                    |
[2022-10-23 01:11:47,577] [util.py:209]               [INFO]     |====================================================================================================|
[2022-10-23 01:11:47,577] [util.py:216]               [INFO]     |                                    Finished Pandemic Collection                                    |
[2022-10-23 01:11:47,577] [util.py:216]               [INFO]     |                                    Collection Run Time: 0:01:12                                    |
[2022-10-23 01:11:47,578] [util.py:220]               [INFO]     |====================================================================================================|
